### ISSUE TITLE
feat: allow hasty touch in safe mode on the crafting simulator

### ISSUE THREAD

**Issue by kronspik** [ffxiv-teamcraft/ffxiv-teamcraft#1026]
I didn't see anyone discussing this. Hasty touch (and HT2/Rapid Synths) can never be 100% success rate, so there's no good reason to block it in safe mode. I think it would be useful to either just straight up allow them or allow them with Steady Hand active only.

**Comment by Supamiu** [comment]
The safe mode is meant to block all the actions that are not 100% success rate. It is here as a helper for people who want 100% reliable rotations.

Allowing HT, HT2 and RS actions would mean that it shows them as safe while they still have a chance to fail, which would go against what safe mode is.

I'm closing this as won't do, because I want to keep safe mode as it is, which means only allowing actions that can't fail at all.
