### ISSUE TITLE
Feat: Ability to make list Emphemeral/Offline after list creation

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1157]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Either in the List drop down or within the list itself, be able to change a list to be Ephemeral and/or Offline after the list has been created. 

**Additional context**
I have some old lists that I created in the past but I have not gotten to. I like the Ephemeral option but changing these old lists can be tedious to set up. Same with Offline. Sometimes I just want a thing done with offline and do not need to have things stored on the site. 

I understand changing a list to offline after-the-fact could cause issues with the database, having to remove items from the online database and creating the list locally in one fell swoop.

**Comment by Supamiu** [comment]
I don't think I'm going to implement these two options, for the following reasons:

 - **Offline switch**: offline lists have a forged ID that cannot be used inside the database because it's not unique accross several TC users, also, having the ability to switch from offline to online using a simple click is too easy and will cause useless stress on database and more cases to be handled (handling properly the case where you toggle it back and forth is going to be a nightmare).

- **Ephemeral switch**: Ephemeral doesn't really make sense anymore, it's still here because it's cool to create but other than that, you have a prompt when you complete a list that is asking what you want to do with the list, an ephemeral list is just clicking on the "delete" for you. But it has more effects on some separated filters that would have to be handled, that's why it cannot be changed on the fly but I don't feel like it's a big UX issue.
