### ISSUE TITLE
feat: compact layout

### ISSUE THREAD

**Issue by ketsugi** [ffxiv-teamcraft/ffxiv-teamcraft#1279]
**Describe the solution you'd like**
A more compact layout (esp for lists) when using the "Always on top" option in desktop app so as to minimize the window size obscuring the game window

**Comment by Supamiu** [comment]
This would mean remove some informations from the list display but I'm thinking about creating an overlay to show current progress for list, assuming you already know how to get the item so it shows no data on how to obtain the item.

Side note, please make sure to use the template, because it would have been cool to see the use case, why you want this and what are the alternative solutions you've considered.

**Comment by Supamiu** [comment]
Fixed by list overlay :)
