### ISSUE TITLE
feat: Less cluttered retainer inventory display in lists

### ISSUE THREAD

**Issue by RobPFarley** [ffxiv-teamcraft/ffxiv-teamcraft#1344]
## What feature are you proposing
I believe the display for items found in retainer inventories could be tidied up slightly within the crafting lists UI. Right now if you have items that are spread across a number of retainers the UI can get extremely cluttered, see the below screenshot.

![retainersclutter](https://user-images.githubusercontent.com/17273366/74043735-d3412880-49c1-11ea-83a5-7d593d7fe2b1.png)

## What is the use case for this feature?
Rather than listing all occurences across all retainers by default I think it would be better to default to a simple "x NQ available, x HQ available" with a button next to it to expand to show the breakdown across retainers/inventory etc, similar to how it exists at the moment. It could also be made so that it only shows this abbreviated display if the item is found across more than say 3 or 4 locations.

**Comment by Supamiu** [comment]
While I agree with the fact that it's really cluttered, I am not sure about the solution you're proposing because these tags are also here to be clicked so it auto-adds the amount to the given list row.

**Comment by RobPFarley** [comment]
Yeah, I was thinking that the shorter version could still be clicked in order to add them to the row, it'll just add the total amount found across all retainers and inventory rather than the individual retainer

**Comment by Supamiu** [comment]
Can you copy your inventory as string and send it to me via pastebin or something please? I'd like to experiment a solution but I need something like you have and it's far from being my inventory :D

To get the inventory, go to devtools, then "Application", in the sidebar of devtools, pick "LocalStorage", then "localhost" and then copy the value associated with "Inventory".

To open devtools on desktop, press Ctrl + Shift + i

**Comment by rcdailey** [comment]
Other optimizations that may improve this:

1. Don't wrap the tags so early. A fully maximized Teamcraft on a 1440p display still wraps way too early.
2. The vertical height of some of the tags has too much whitespace in it. The height is uneven for some of them.

Another idea: Instead of wrapping at all, just keep listing them horizontally until space runs out. At which point you collapse the ones that don't fit into a "..." button that the user can click to get a pop-out menu of these to click on, which add numbers to the total amount as they do today.

So as you expand/shorten the width of the window, more tags get unpacked/packed out of / into the overflow menu.

**Comment by Vassi** [comment]
You could also have an Inventory and 'Retainers' tag that aggregates the amount on the retainers at a glance but behaves like a dropdown to fill the order from a retainer. Kind of how the add alarm tag functions now, to add an alarm to a list?
