### ISSUE TITLE
Bug: Inventory sync not turning on

### ISSUE THREAD

**Issue by efreebairn** [ffxiv-teamcraft/ffxiv-teamcraft#1349]
## Environment
Windows 10, desktop app, version 6.5.12

## Current behavior
Inventory syncing does not turn on, even when I follow the instructions and teleport to a new location/enter a house and open my chocobo saddlebags. 

## Expected behavior
After seeing the popup, teleporting or entering a house should make it go away, and I should see my inventory information. 

## Steps to reproduce
1. Open teamcraft list, see popup "Please change zone (by either teleporting or entering a house) in order to update your inventory. This popup will close once it's done." 
2. Teleport to a new location or enter a house. 
3. Nothing happens to the list with the popup.

For additional context, I have inventory syncing working on another computer. I do not have ffxiv or teamcraft open on that computer while I'm trying to set it up here.

**Comment by Supamiu** [comment]
There's a troubleshooting channel on discord with people to help with this kind of issue, please consider using it instead of github issues, as this is not a bug, more a missconfiguration due to how complex and boring the setup for firewall and all this is.

Here is the pinned message about troubleshooting packet capture, hope it helps:

***Attention PS4 Players***
*Packet capture does not work for the PS4, only on PC*

**Here is a checklist for packet capture feature:**
 - Is your app up to date (see #announcements )?
 - Are you using Desktop app?
 - Is the app started as admin?
 - Do you have MachinaWrapper.exe authorized for inbound traffic inside the firewall (C:\Users\name\AppData\Local\Programs\ffxiv-teamcraft\resources\MachinaWrapper)?

**If the above 4 are true then do the following:**

 - With the app opened, open devtools and type window.debugPackets = true; then press enter, then move in the game and TP to a new zone, do you see any output?
 - Try to install npcap (https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe) and add -wp to the Teamcraft shortcut.

**Comment by efreebairn** [comment]
I have uninstalled and reinstalled with new version 7.0.0 and i'm getting the same problem. Running as admin, have the firewall rule added to windows firewall. I even restarted my computer after setting up the rule. I have enabled the debugPackets output, and I see output when I teleport to a new zone. No error messages. I will try to install npcap and see what happens. 

Per your suggestion, I can also move this to the troubleshooting section of discord. Feel free to close this issue if that's better.

**Comment by Supamiu** [comment]
It'd be better yeah :) discord is where most of the announcements are made, including one about the fact that packet capture needs to be authorized in the firewall again ^^

Anyways, this will not be an issue anymore with 7.0.1 as I'm adding automated firewall rules.
