### ISSUE TITLE
Bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by techsrus** [ffxiv-teamcraft/ffxiv-teamcraft#1401]
**Describe the bug**
When I try to install the executable it shows a loading graphic and then I am met with this error:

A Javascript error occurred in the main process

Uncaught exception:
TypeError: Error processing argument at index 0, conversion failure from undefined at createWindow (\AppData\Local\ffxiv-teamcraft\app-7.0.7\resources\app.asar\desktop\main.js:210:7)
at App.<anonymous> (\AppData\Local\ffxiv-teamcraft\app-7.0.7\resources\app.asar\desktop\main.js:444:3) at App.emit (events.js:208:15)

**To Reproduce**
1. Run the exe.
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version - Tried desktop 7.0.7, 7.0.6

**Comment by cmcm951102** [comment]
you need node.js , I guess.

**Comment by Supamiu** [comment]
You don't need nodejs to run Teamcraft, it's a bug because of a change I made to the alwaysOnTop system.

It has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/f94ec46f24237ac7c8af72623b2932ad32038393 and will be in 7.0.8 :)

In the meantime, you can install 7.0.5 and update from here.
