### ISSUE TITLE
feat: Allow for custom rotations to be shared with pre-configured stats?

### ISSUE THREAD

**Issue by Rietty** [ffxiv-teamcraft/ffxiv-teamcraft#1409]
So a major point when sharing rotations/helping people out is that they create a rotation, I have to open the link, then click the stats/class level, adjust it to their level and then help fix/work on rotation. I feel as if this could be simplified by adding the stat/level/class information to URL maybe or some other method so when you share rotation, the stats and such are shared with it. Would simplify a lot of things.

**Comment by Supamiu** [comment]
Since 7.0.0, you can share a rotation with stats (I don't know why but it's not inside the patch notes).

Example: 
![WuZiVDjOeO](https://user-images.githubusercontent.com/11519203/75552276-3f99cf80-5a36-11ea-8d0f-65ca4d2f496d.gif)


Here is the link I copied in this gif: https://ffxivteamcraft.com/simulator/29422/33819/gTeTpj4n88EAqmFwUzA6?stats=2468/2451/556/80/1

**Comment by Rietty** [comment]
@Supamiu Thanks Miu! I love you. :D
