### ISSUE TITLE
bug: Universalis integration  updates wrong server

### ISSUE THREAD

**Issue by sonpansatan** [ffxiv-teamcraft/ffxiv-teamcraft#1451]
**Describe the bug**
When using the universalis marketboard integration feature, the information is sometimes updated for the wrong server, causing prices to become incorrect.

**To Reproduce**
1. Be on Crystal datacenter (possibly optional)
2. Start both FFXIV and Teamcraft.
3. Go to Limsa Lominsa Aetheryte (possibly optional)
4. Open a page in Universalis for an item.
5. View the same item in the Marketboard.
6. After waiting a few seconds, refresh the Universalis page.
7. Use the Server Visit feature to go to a diffrent server.
8. After repearing steps 5-7 several times, the server that is updates in Universalis will not be for the server you are on, but the server you were previously at.  This will not happen all the time, so several visits will be necessary.

**Expected behavior**
When viewing an item's marketboard information, it should be for the server that I am currently on.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Desktop App is 7.0.12

**Comment by SapphicFire** [comment]
After a preliminary review and with the consideration that the issue has been intermittent, it would appear that the issue is with the usage of _shareReplay_ within _worldId$_ and this information being out of sync, possibly due to order and response times. Will need further investigation

https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/0a1ed0d7db0e97da0e2c15fbb4e4c82b88f546f7/apps/client/src/app/core/api/universalis.service.ts#L22-L27

**Comment by Supamiu** [comment]
Seems like the above comit fixed it, thank you @SapphicFire :)
