### ISSUE TITLE
feat: Disable retainers on a different data center

### ISSUE THREAD

**Issue by stevenhay** [ffxiv-teamcraft/ffxiv-teamcraft#1569]
I have two characters on two different data centers, when I'm creating lists I can see items from my retainers on a different data center. I'd prefer to only see the retainers on the character (or data center) I'm on, as the ones on other data centers are unusable.

I'd like there to be an option which allows me to only show current usable retainers.

**Additional context**
All retainers below crossed out in red are unusable for the currently selected character. 

![image](https://user-images.githubusercontent.com/26744309/89405440-783f8280-d713-11ea-9ffb-bfd1fd2b5e4e.png)

**Comment by stevenhay** [comment]
I believe, even as a rudimentary approach, this should be possible by simply keeping track of which server the retainers are on and thus you can determine the data center. When the user swaps between accounts in teamcraft, only show the retainers available on that data center.

Thoughts? At the very least it'll stop completely unusable retainers from showing up.

**Comment by Supamiu** [comment]
Hello, sorry for the late reply, I had a lot of IRL stuff to do ^^".

Filtering retainers and even character inventories based on your current datacenter or current character is a big chunk of work, because inventories are hard to sync properly and dealing with the constant character swap is a pain (because the ingame informations we get about your character aren't using the same identifiers as lodestone, so we have to bind them using name/server combination, which requires you to log in iirc).

For now, you can go to the settings and ignore the inventories you don't want to watch anymore, they'll be ignored everywhere, including lists and inventory optimizers.

**Comment by stevenhay** [comment]
Ah I didn't realise you could ignore some inventories -- I'll do it manually for now! Thank you for all your hard work <3

**Comment by Supamiu** [comment]
I'm closing this because it'll be automatically handled once we can properly handle multiple character inventories (even if I have no idea when this will be tbh).
