### ISSUE TITLE
Adding certain submarine parts to a crafting lists makes the list behave in auto-collapse way.

### ISSUE THREAD

**Issue by msoltyspl** [ffxiv-teamcraft/ffxiv-teamcraft#1609]
**Describe the bug**
As in subject - after adding certain components, the list behaves in "auto-collapse every section" way. Including reopening the list.

**To Reproduce**

1. Create new list
2. Open the list
3. Add "Syldra-class Bridge"
4. Add "Unkiu-class Stern"
5. Add "Modified Unkiu-class Stern"
6. Add "Modified Shark-class Bow"

At this point the list sections will auto-collapse.

- The order of additions doesn't seem to matter.
- The layout used doesn't seem to matter.
- List remains fully collapsed every time one opens the list.
- Removing any of the above items from the list will make the list behave normally again.

**Expected behavior**
Don't auto-collapse everything

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Vivaldi (3.2.1967.47 (Stable channel) (64-bit) + earlier versions)
 - Desktop app: 7.3.11 and a good few versions backwards

**Smartphone (please complete the following information):**
N/A, not using the app on smartphone.

**Additional context**
N/A

**Comment by Supamiu** [comment]
THe list starts as auto-collapsed because it is too large to be seen in a single screen, the main goal is also to remove the load on the renderer by collapsing large lists automatically.

Adding several submarine parts creates a list over 100 total items (final + materials), which is the limit to have the list panels collapsed by default.

**Comment by Supamiu** [comment]
This issue isn't going to be fixed because this is by design, larger lists are opening as collapsed and that's in order to prevent performance issues with them.

That being said, I'm going to change the auto collapse way to be per-panel, only when the panel includes more than 25 items, which should be better for your use-case.
