### ISSUE TITLE
feat: list creation from multi-line user input

### ISSUE THREAD

**Issue by SalvatoryMalamar** [ffxiv-teamcraft/ffxiv-teamcraft#1655]
**Is your feature request related to a problem? Please describe.**
I often have an external list of items (with exact names copied from TC earlier) I need to craft and it is tedious to add these items to a TC list one-by one using the search feature. This is because there is a delay in Teamcraft between a search and the item being returned. The delay adds up for multiple items. 

Often I have this list of items to craft because I externally keep track of what items I'm selling, and at the beginning of the day I may have to bulk craft items to replace what was sold.

Other times, I had created a large list in Teamcraft of items to craft and I crafted all the items I had materials for. I will return to the list after collecting the missing materials. When I try to use the existing TC list for the remaining items it is be difficult for me to discern which items were newly crafted. I need to discern which items I successfully crafted in order to update my master inventory of items I sell (see context at the bottom for details). 

**A clear and concise description of what you want to happen.**
- I would like to have some way to copy and paste my external list into Teamcraft to create a new list. There could be an icon beside the search box to "expand" the input into a text box. 
- After I enter the items, Teamcraft could present me with an error message displaying the names of items that were not found so I could manually search and add them via the existing search method. 
- Teamcraft would populate the list and each item would have a quantity of 1. I could go to my lists page to adjust the quantity for each item. Or, Teamcraft could present me with a version of what is displayed on the lists page when the disclosure triangle is clicked so item quantities could be adjusted. 

**Describe alternatives you've considered**
I've tried resetting a TC list and "filling with inventory" when I have a few items that I had to go and collect materials for (but I have already crafted the remainder in the mean time). This is partially useful if I have already collected the materials for the missing items. However, if I have not already collected the materials, then it is difficult for me to know which materials are needed for the uncrafted items. Also, sometimes the pre-craft/gathering lists can be unnecessary long with all the old items, it is difficult to quickly identify materials needed, and Teamcraft slows down for only a handful of items to be crafted. This does not address the frustrations of adding multiple items via search when I already have the exact item name.

**Additional context**
I maintain an external inventory of all the items I craft for selling. The attached images show how I manage as a merchant. I'm always looking for ways to format my inventory to better work with the amazing features Teamcraft provides. In this rare case I think a new feature to TC might help make things a little more efficient.

![overview](https://user-images.githubusercontent.com/56521874/95015017-a4df2000-0618-11eb-94fc-2e6ee30fe090.jpg)

![inventory](https://user-images.githubusercontent.com/56521874/95015021-a872a700-0618-11eb-8d28-3ccbbb0c7457.jpg)

**Comment by Supamiu** [comment]
Hey, did you check https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/wiki/Connect-with-FFXIV-Teamcraft ?

I feel like creating an import feature for every single format isn't the way to go because then it'll need an implementation for every single possible source format, and I don't want that. This is why this API exists.

To find the id of an item, you can use the items.json file on github cdn here: https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/staging/apps/client/src/assets/data/items.json

**Comment by SalvatoryMalamar** [comment]
Hi Supamiu. Thank you for directing me to that useful guide on connecting with Teamcraft. I think I can make use of that. 

Just to clarify, I would suggest that the user could input a number of item names separated by carriage returns to form a list. From your reply I got the idea that perhaps you thought I was requesting the support of a more specialized format. I'm not sure if that was the case or not, and I thought it may still be useful to clarify. I completely understand if such a request is too specialized to warrant development focus.

**Comment by Supamiu** [comment]
It might be worth creating a small tool to input item names and quantity and create a list from that using the list endpoint provided above, but yeah I don't think this is worth a feature inside Teamcraft, especially because it'll end up having search at some point if we want to validate input, and that's the slow part.

That being said, there's a feature request for a kind of "cart" where you can search for items and add them to a temporary list inside the search page (#1436), this might be closer to what you're looking for.
