### ISSUE TITLE
bug: Blue "Materials Acquired" Indicators do not Account for Consumed Materials

### ISSUE THREAD

**Issue by b-sen** [ffxiv-teamcraft/ffxiv-teamcraft#1721]
**Describe the bug**
When working to craft items in a list, there are two visual indicators to say "you have the materials to craft this item": a dotted blue line around the item if precrafts are needed before making it, and a solid blue background if the craft can be started immediately.  These indicators do not account for if those materials were consumed in crafting a different item, and therefore no longer available.

**To Reproduce**
1. Create a new list.
2. In this list, add 1 Darksteel Rings and 1 Darksteel Rivets as final products.
3. The list will populate with 2 Darksteel Nuggets as required precrafts, 1 for each final product.
4. Add as external exactly 1 Darksteel Nugget to the required precrafts, enough to complete either but not both final products.  Observe that both final products (correctly) light up with solid blue backgrounds.
5. Check off the Darksteel Rings, consuming the Darksteel Nugget to complete the item.  Open the Inventory view of the list and verify that no Darksteel Nuggets are still present to be crafted with.
6. Observe that the Darksteel Rivets still have a solid blue background, even though the list has been told that all acquired nuggets have already been consumed.

**Expected behavior**
I expect that if materials are no longer available because they have been consumed by another craft, the indicators will update to reflect this.  In the above example to reproduce, the Darksteel Rivets would lose their blue background when the Darksteel Rings are marked completed, since they cannot be crafted without acquiring another Darksteel Nugget.

**Screenshots**
![Example Reproduction](https://user-images.githubusercontent.com/794427/100698880-8d49bc80-3367-11eb-9367-680aedb4ceae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Desktop app v7.5.6

**Comment by b-sen** [comment]
I have recently noticed, although it is hard to definitively isolate in practical lists, that similar issues with the indicators can appear when checking off crafts that imply precrafts or materials gathered.  (In the reproduction example, consider starting immediately after step 3 and then checking off the Darksteel Rivets, implying that a Darksteel Nugget was crafted and then consumed.  The Darksteel Rings might light up blue or dotted blue.)  I suspect this is due to the same bug, occurring as precrafts and materials are propagated through the list from a "can this item be crafted?" check happening after the implied precrafts / materials are checked off in the list but before they are marked as consumed.

Here's an example I managed to get three times in a row on desktop v7.6.16.  Perhaps it is consistent or diagnostically useful?
![Example where the Darksteel Rings get a dotted blue outline, presumably from a check going off while the ore is marked as available.](https://user-images.githubusercontent.com/794427/103119728-9bc38500-4642-11eb-9661-b93535aac464.png)

**Comment by Supamiu** [comment]
This most likely is coming from the fact that the `used` counter is never reduced, always increased. The reason for this being recipes that yield many items at once.

For instance, let's say you're crafting 6 `Kudzu Thread` (a recipe that yields 3 items). And you're adding 3 threads, then removing 2. This means that technically, the mats are still consumed, because you didn't remove an entire craft, but maybe the thing is that you failed another craft and need 2 more kudzu thread, which means that you in fact need another kudzu craft.

This is why I decided to never make the counters go down but always up, so reducing a final item by 1 means that nothing will change in the `used` field, except if you reset the list, in which case everything goes back to 0.

I would love to have a real solution to this issue tho, but I couldn't find one yet, because it' smostly an UX choice.
