### ISSUE TITLE
bug: Teamcraft desktop requires Admin permissions if winpcap is turned on for capture

### ISSUE THREAD

**Issue by highlyunavailable** [ffxiv-teamcraft/ffxiv-teamcraft#1760]
**Describe the bug**
When using the "Use winpcap for packet capture" option, Teamcraft desktop still requires admin permissions to launch.

**To Reproduce**
1. Go to settings/desktop
2. Enable "Enabled packet capture" and "Use winpcap for packet capture".
3. Restart Teamcraft desktop.

**Expected behavior**
Teamcraft Desktop does not request admin permissions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: desktop app
 - Version: v7.6.11

**Smartphone (please complete the following information):**
N/A

**Additional context**
The reason to use winpcap for packet capture is so that the application can connect to the driver for packets and not run as administrator. Using the app as administrator breaks many things, such as Discord push-to-talk when Teamcraft desktop has window focus, so I'd prefer to run it without admin permissions. ACT uses the same method (winpcap) and can safely run without administrator permissions if using winpcap.

**Comment by Supamiu** [comment]
That's not really a bug since it's mostly caused by electron being a nightmare when it comes to UAC interactions and spawning elevated processes. That's the main reason why the main TC process requires admin at the moment.

I'm taking a look at it and digging a bit to see what I can do for that, maybe it'll work properly using an `exec` wrapper but I'm still not entirely sure.

**Comment by highlyunavailable** [comment]
Yeah, I figured it was due to electron + needing admin for non-winpcap. I also thought it'd be worth raising as an issue in case it could be fixed.

**Comment by Supamiu** [comment]
With 7.6.12 I made admin permissions optional to start winpcap but TC still asks for admin permissions when starting. Because the only solution I found to spawn an admin process inside the wrapper was to have it use `atom/spawn-as-admin`, which itself is a gyp binding using C code, and it is not building on my machine for some reason atm.

Needless to say it'll also be a nightmare to build inside circleci, so i'm keeping the branch for now, and maybe keeping this issue opened too, but I have no idea how to do that in a clean way tbh 😞

**Comment by allainecactuar** [comment]
If you really want to run Teamcraft without admin permissions, you can use the `RunAsInvoker` windows compatability setting. This is not in the usual UI unless you've installed some advance app compat toolkit stuff, but you can still use it by setting an environment variable. 

Here's an example batch file:

```
set __COMPAT_LAYER=RUNASINVOKER
"%LocalAppData%\ffxiv-teamcraft\FFXIV Teamcraft.exe"
```

**Comment by highlyunavailable** [comment]
> set __COMPAT_LAYER=RUNASINVOKER
> "%LocalAppData%\ffxiv-teamcraft\FFXIV Teamcraft.exe"

Spicy, but I like it. It's certainly a viable workaround for me right now as my main issue was "if I'm doing stuff in teamcraft, PTT in Discord stops working" and this works to stop that.
