### ISSUE TITLE
feat: Ability to search/filter by "stars" without having to know names/recipe levels

### ISSUE THREAD

**Issue by highlyunavailable** [ffxiv-teamcraft/ffxiv-teamcraft#1776]
**Is your feature request related to a problem? Please describe.**
I commonly want to search for items with stars (e.g. a 50 3star or a 70 4star), or gathering items (e.g. all 80 4star nodes) but the search UI doesn't have the ability to filter by "stars", only by item level/recipe level.

**Describe the solution you'd like**
Both the recipe search UI and the gathering item UI should be able to filter by level and "star", so I can request a list of 80 4 star nodes or a 60 3 star recipes without having to find the item names somewhere else and search by name.

**Describe alternatives you've considered**
There really isn't a good alternative other than finding names and searching that way.

**Additional Context**
A possible UI could be like this:
![image](https://user-images.githubusercontent.com/6266125/103179057-16f08b00-483d-11eb-9e27-8a815876a157.png)

**Comment by Supamiu** [comment]
Hi,

The recipe level inside this filter is the level required to craft the item, not the actual level of the recipe (which is a value hidden to the user ingame).

I think what's really needed is to change the label of this search filter, because there's no "gathering item" filter and no "rlvl" filter, so this can simply not be done.

**Comment by highlyunavailable** [comment]
The data is clearly there (since recipes are displayed as 80 3* and such in the crafting interface) and RLevel doesn't appear to be displayed in game at all. I was partially requesting a "gathering item" filter as well, since it's a common use case I have, hence the _feature request_.

Anyway, we seem to have very different use cases for github as well (I'm more used to the style where an issue is a thread to hash it out and then a PR is the action) but whatever. Sorry for bothering you.

**Comment by Supamiu** [comment]
It's not because you see something ingame that it's easy to get, use and filter. And this is especially true inside ffxiv stuff.

As for the gathering search, you have both gathering-location page and log tracker to find a gathering item easily, I understand that filtering by level + stars would be easy, but the implementation would be really complex and unreliable, plus it would require manual maintenance on patches that give new content to have the binding between # of stars and the corresponding ilvl.

**Comment by highlyunavailable** [comment]
Sorry, but you're already doing the binding obviously, or at least finding some way to do it, and the data is available by inferring from what I can see - anything ingredient that has the same ILevel as a recipe with detected "stars" is the same star level of gather. As you said though, no discussion, so that's that.

![image](https://user-images.githubusercontent.com/6266125/103181425-a1dd7f80-4855-11eb-9dc2-81eed8c67c19.png)

**Comment by ayyaruq** [comment]
For some context, star bindings come from the recipe level table which is included in the linked data we get in lists, but not search. We can display it in a list or the simulator because it's already there. Search doesn't expose stars so we can't filter by it unless we manually maintain a mapping in the TC codebase, so we don't have any way to infer it and it's not clearly there at all.

Unrelated, I don't think gathering 4-star exists. There also isn't a direct correlation of crafting stars to gathering, they're used entirely differently in the game data.
