### ISSUE TITLE
bug: When Gathering is Level 0, it doesn't remove them from "Only show what I can do"

### ISSUE THREAD

**Issue by axipher** [ffxiv-teamcraft/ffxiv-teamcraft#1849]
**Describe the bug**
I have only started Botany and are therefore Level 0 in Mining and Fishing.  If I leave my profile as Level 0 in Mining and Fishing then create a list of items and check the box for "Only show what I can do", it still shows gathering items that are mining or fishing.

If I then go in to my profile and set Mining and Fishing to Level 1, then it correctly removes those gathering items and only lists the pre-made items instead.

It also seems like the check-box for "Only show what I can do" just doesn't consistently work.

**To Reproduce**
1. Per above, just set gathering levels to either 0 or 1 to see the items show up in your gathering parts of a list

**Expected behavior**
It should correctly show all materials as gatherable until you click the "Only show what I can do" check-box then it should properly remove Gathering items for jobs at level 0 or that require a higher gathering level then you have in your profile.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest web???

**Additional context**

**Comment by Supamiu** [comment]
This is kind of intended but needs better detection imo.

The idea is that if your profile isn't filled, your levels are 0 and it means that we don't know what they really are, so we assume you just have everything max level, which is convenient for anonymous users opening a ist for the first time, so they get a normal display instead of every crafts in other and stuff.

However, I think it should detect that all the levels are 0 before doing that, not just the one that's being considered in the filter.

**Comment by axipher** [comment]
> This is kind of intended but needs better detection imo.
> 
> The idea is that if your profile isn't filled, your levels are 0 and it means that we don't know what they really are, so we assume you just have everything max level, which is convenient for anonymous users opening a ist for the first time, so they get a normal display instead of every crafts in other and stuff.
> 
> However, I think it should detect that all the levels are 0 before doing that, not just the one that's being considered in the filter.

That makes sense to make that assumption for higher level or more dedicated players that would typically use a tool like this. 
 Maybe have the default be -1 if it's not filled in to represent max level, that way people can put in 0 themselves afterwards.

Alternatively, a checkbox for "Untrained" could work too that users could check for the skills/jobs they haven't started yet.  Maybe on initial profile sync, you could also have a checkbox for "Start all jobs untrained".

**Comment by Supamiu** [comment]
Your solution is good but it won't work in the current context, because it would only work on new profiles.

The checkbox would be too specific for people to use it properly imo, and would take space for only a very low % of the users to actually use it.

I think we can safely assume that if at least one level is filled, the user already filled their levels and therefore, the levels that are set to 0 are locked, because you cannot be level 0 ingame 🙂

**Comment by axipher** [comment]
That would be a fair assumption to make if a user has explicitly filled in at least one level to treat the 0's as untrained at that point.

Can I leave this with yourself and the Teamcraft team to close once something has been decided and implemented?  I'm happy to test, but I feel this is a pretty simple thing for the team to test.
