### ISSUE TITLE
feat: Sightseeing Log timer

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1880]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Under Helpers -> Log Tracker (or some other location) add a tab for Sightseeing Timers. Similar to [Tylian Sightseeing Log Helper](https://tylian.net/sslog/). This mostly focuses on ARR Sightseeing Logs but there are a few in Heavensward and Stormblood content that require time requirements.

**Additional context**
Just going through some logs in-game and noticed a Sightseeing Log was not part of the program.

**Comment by Supamiu** [comment]
I'm going to close this as won't do, because I don't want to maintain tooling that only relies on handmade data, this is because it would require someone to actually contribute the data, and seeing how something as used as the garlandtools sheet is updated (basically 3 people updating it for everyone), I don't see it being maintained properly. The data required isn't inside the game files, which makes this impossible in an automated way.

That being said, someone made an alarm folder with all the current sightseeing log entries that require a timer, it can be found and cloned here: https://ffxivteamcraft.com/alarm-group/EKblxCY58GFdqd5YNgho

Small standalone tools maintained by dedicated people are way better than having this inside Teamcraft where I won't have time nor knowledge to maintain it properly, making it obsolete in a couple of game updates.
