### ISSUE TITLE
bug: completed log with "hide completed items" hides the toggle too

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1881]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
So if you marked all Log items as being completed as well as hide completed Items, you will come to a blank screen that has no way of resetting or showing any items.

**To Reproduce**
1. Go to Helpers->Log Tracker
2. Select one of the jobs
3. Mark all items as being completed
4. Select Hide completed items

**Expected behavior**
Some way of un-hide completed items

**Screenshots**
https://i.gyazo.com/a6ff6bcf1313e3c7b19fa5cb737b7576.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.1.6

**Comment by Supamiu** [comment]
Hi,

This is not a bug, it's a feature request, and to be honest I don't see the point of resetting the log for the users, it's not like it can be reset ingame.

The bug you're reporting is not related to a way to reset or anything, it's related to the toggle not being shown when all pages are completed due to not having a page to attach to.
