### ISSUE TITLE
feat: export fishing log completion to CarbunclePlushy

### ISSUE THREAD

**Issue by Lodinn** [ffxiv-teamcraft/ffxiv-teamcraft#1905]
**Is your feature request related to a problem? Please describe.**
Currently, TC seems to support import from carby but not the export (fishing-log-tracker.component.ts).
There are users requesting the export feature every now and then, seeing how TC can autofill the log entries.

**Describe the solution you'd like**
An export function to produce a json dumps-like text to be copied and pasted to carby.

**Describe alternatives you've considered**
Doing it by hand. Clearly sucks.

**Additional context**
Currently, carby uses "completed" key for the caught fish ID list.

**Comment by Supamiu** [comment]
This is possible but since Carby has an "export settings" feature, producing a JSON for the import version of this would mean overriding your current progression with TC's progression, and resetting your settings.

ideally, this would require Carby to have an import feature that just imports a completion array and patches the current saved progression with the new one from Teamcraft, making it non-destructive including for settings.

@icykoneko will know more about if this is possible or not on carby's side 🙂

**Comment by icykoneko** [comment]
Hey thanks for the ping.  Lalachievments same to me with a similar request a while back, and what we settled on was to allow the import feature accept a single, JSON formatted array of "item IDs", namely, the fish (or any "fish" that are caught - i.e. minions).

Take a look at https://github.com/icykoneko/ff14-fish-tracker-app/wiki/Checklist-Updating-Tips#importing-from-teamcraft.  This is how I've been exporting the data from TC.  Just provide that string to your users, and maybe give them basic instructions on where to look on mine to complete the import process.

With regards to, but this would blow away their progress on my tracker... meh, that's why it's called import haha.  If my users want for a sync feature, I'll handle that on my end.

**Comment by Lodinn** [comment]
On Carby's side, this is seemingly rather trivial; as already said, catched list override is an acceptable behavior and besides, keeping the current progress is literally a matter of one line of code ^^
