### ISSUE TITLE
bug: Searching Bugs out for Slow Typers. Some Typed Information is Lost.

### ISSUE THREAD

**Issue by Ryonez** [ffxiv-teamcraft/ffxiv-teamcraft#2056]
**Describe the bug**
When searching for an item, typed characters can end up missing. This happens when you have a slow typer, and it attempts to make a search while the person is still typing.

**To Reproduce**
1. Go to 'Search'
2. Type something into the search box, but slowly.
3. See characters can end up missing.

**Expected behavior**
For a user to be able to search for an item that they type in.

**Screenshots**
Video of the issue here: https://xbackbone.alteria.xyz/canI3/cOJABOsO07.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Ferdi
 - Version: 9
 
**Additional context**
Friend has confirmed they can replicate it themselves using Chrome.

**Comment by Supamiu** [comment]
Hi, thanks for your report.

For slower typers, you can enable the "Disable search debounce (only pressing enter will trigger search)" setting inside the settings popup.

The main issue with this is that search uses a debounce, which is a given value atm (1200ms iirc), and if increased, it'll make search better for slow typers but slower for people typing faster, because no matter what you'll have to wait the debounce time before considering that the user is done, that's why this settings exists.

**Comment by Ryonez** [comment]
Disabling the debounce is a perfect solution for me, thank you.

It there a possibility to maybe make that timeout configurable by the user? That would make it a bit easier for slower people who would appreciated having the feature enabled.

**Comment by Supamiu** [comment]
It's not possible without many hanges inside the codebase to reapply the timeout dynamically, it's too technical to be exposed to the user imo.

I'm closing this issue as your problem has been resolved 👍

**Comment by Ryonez** [comment]
I see, that's a pity.
Thanks again.
