### ISSUE TITLE
bug: Rotation frame disappeared when create or view a rotation in crafting simulator.

### ISSUE THREAD

**Issue by RikaKagurasaka** [ffxiv-teamcraft/ffxiv-teamcraft#2059]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**

The below part of simulator disappears, while in console there are `Cannot read properties of undefined (reading 'toString')` errors.

The bug presents in both web and app version no matter if I logged or not.

However, there are no errors when I create a custom rotation.

**To Reproduce**
Enter crafting simulator with selecting any item.

**Screenshots**
![image](https://user-images.githubusercontent.com/22655313/142376700-e4bab2c1-f7e5-49fe-8ab1-5a22854de04a.png)
![image](https://user-images.githubusercontent.com/22655313/142376891-76e229d0-5ee4-4089-9d07-2dd2a81143b8.png)
![image](https://user-images.githubusercontent.com/22655313/142377372-cfeed149-b7c9-47ca-92d4-6f0754fae1c8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge or Desktop app
 - Version: 9.0.2

**Additional context**
May be it a network problem? I have a proxy configured.

**Comment by Supamiu** [comment]
Fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/pull/2060/commits/70f4e4c17ee50a7243e346ca86dc150ae56fd4ec, which is being released as this comment is posted 😄 .

Thanks for your report, I just wanted to add that for reports, specifying your region is important, as you can see in the commit message I linked above, this was only affecting Chinese dans Korean regions.
