### ISSUE TITLE
bug: "Mark whole panel HQ" doesn't work

### ISSUE THREAD

**Issue by Uriei** [ffxiv-teamcraft/ffxiv-teamcraft#2091]
**Describe the bug**
On a crafting list, clicking the "Mark whole panel HQ" button does nothing, not even a log on the console.

**To Reproduce**
1. Go to a list
2. Click on 'Mark whole panel HQ' on the final item list. (It does work on Pre crafts, per example)
3. Does nothing

**Expected behavior**
Marking all items to craft as HQ without having to go one by one

**Screenshots**
![image](https://user-images.githubusercontent.com/6078221/145568390-edaf26f1-ee97-4dd5-a3e2-a98125cc1e9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10x64
 - Browser: Vivaldi
 - Version: 5.0.2497.28 (Stable channel) (64-bit)

**Comment by Supamiu** [comment]
This behavior is not supposed to be possible for final items panel, because the final items are implcitly waned as HQ whenever it's possible, that's why they don't have the manual HQ icon on them, because the HQ icon means that you want this material as HQ to make the end craft easier.

I'll remove the button from the final items panel, because that's the real issue, it doesn't make sense here and that's why it's not working.
