### ISSUE TITLE
bug: Scripts served from CDN have no `max-age` cache header.

### ISSUE THREAD

**Issue by alercah** [ffxiv-teamcraft/ffxiv-teamcraft#2106]
**Describe the bug**
Scripts served from the CDN are not marked as cacheable by th

**To Reproduce**
1. `wget -S https://cdn.ffxivteamcraft.com/main.4c6b6344fb934d046ff4.js`

**Expected behavior**
The headers include a `Cache-Control` with a long `max-age`

**Actual behaviour**
There is no `Cache-Control` header.

**Desktop (please complete the following information):**
 - OS: Debian stable

**Additional context**
Because scripts in the CDN are content-addressed, a very long cache time is appropriate. One year is common.

Currently, it appears that Chrome, at least, revalidates its cached copy every time I load the page. This means an extra round-trip to the server to check that the script hasn't changed, although chrome doesn't actually redownload the script each time.

**Comment by Supamiu** [comment]
Hi, thanks for your report.

This seems like it's an issue on cloudflare itself, since the cache is hit on their side anyways.

Let me know if you have more informations on how to configure that on CF's side, since that's where the headers are not being passed on properly.

The original content hosting server has a 1y cache set and I think this roundtrip is intended in ClourFlare's design.

This might be a wontfix if you don't have more informations about changing that in CloudFlare or if it's worth preventing this small roundtrip at all.

**Comment by alercah** [comment]
This is the docs I can find:
https://developers.cloudflare.com/cache/how-to/set-browser-ttl.

But I'm not familiar with how CloudFlare actually gets configured or how to
debug it.

I imagine removing these round trips would speed up loading the app when
visiting it for the first time in a session. I couldn't tell you by how
much, though.

**Comment by Supamiu** [comment]
CLosing as I just appliued the changes to CF and that's about how much I can do :/

**Comment by alercah** [comment]
That fixed it! Thanks!
