### ISSUE TITLE
feat: Pull data from Lodestone

### ISSUE THREAD

**Issue by jessemillar** [ffxiv-teamcraft/ffxiv-teamcraft#2135]
**Is your feature request related to a problem? Please describe.**
For those of us that want the powers of Teamcraft (particularly the inventory optimizer and recipe finder) without breaking ToS with packet captures, there's a good bit of manual effort involved. I think it could be simplified even further.

**Describe the solution you'd like**
Would it be possible to poll data from Lodestone for retainer inventory? I've found the Chrome extension that allows for quick JSON copypasta of the inventory data but is there anything stopping Teamcraft from automatically downloading this data via a scraper since it already knows my character's Lodestone ID?

**Describe alternatives you've considered**
I could always just build a separate command line tool or website for myself with only the inventory management features I personally want based on the polled data, but that doesn't help the community.

**Additional context**
I'd potentially be willing to help contribute the additional feature if there's not an obvious reason why it wouldn't work (e.g. rate limiting, already tried, etc.).

**Comment by jessemillar** [comment]
Ahhhh. I just realized the retainer inventory page is not available unless you're logged in on Lodestone. I'd guess we'd need either an official Square Enix OAuth API (which likely doesn't exist) or storing of user's passwords to log in which is a definite violation of ToS.

**Comment by Supamiu** [comment]
That's what I was about to say, cannot be done but pacet capture cannot be detected and you're safe to go with it since ToS technically disallows every 3rd party tools, which includes Discord (Yoshida said it themselves).

Closing as impossible to do ^^ but thanks for willing to contribute, let me know if there's something you want to implement (and possibly join discord server to make it easier to chat about it)
