### ISSUE TITLE
feat: Dalamud Macro Chain Plugin Support, or Dalamud Plugin with integration as a whole

### ISSUE THREAD

**Issue by Praedyth-Rey** [ffxiv-teamcraft/ffxiv-teamcraft#2165]
**Is your feature request related to a problem? Please describe.**
I'm currently going through crafter relic gathering because procrastinating doing story, and I realized, it'd be really neat to be able to have support for the Macro Chain plugin for the Dalamud API with its /nextmacro command, which starts the next macro in your list. And while writing this, I realized oh wait, what if there was a plugin from Teamcraft that straight up injected the macros for you or did the rotations for you automatically.

**Describe the solution you'd like**
A toggleable option to include /nextmacro into multi-macro craft macros, either on a per-rotation-instance basis or an account/cookie wide basis. And as I mentioned above, injecting the macros into the lowest numbered empty spot, with support for the aforementioned Macro Chain to find two or more next to each other.

**Describe alternatives you've considered**
Noooooooot really tbh.

**Additional context**
None. Thanks for your time tho and enjoy the idea!

**Comment by Supamiu** [comment]
This isn't something we want to support, because this plugin is too close from automating the game.

If you want such a support, make a script to adapt the macros.

Also the app doesn't interact with the game at all, to avoid opening a can of worms that I don't want to open, so Teamcraft will never copy the macros in your game client for you.
