### ISSUE TITLE
feat: mark complete gathering/items/pre-craft on list overlay

### ISSUE THREAD

**Issue by spiral6** [ffxiv-teamcraft/ffxiv-teamcraft#2197]
**Is your feature request related to a problem? Please describe.**
It would be very useful for me to mark things complete in the overlay rather than swapping to the main Teamcraft window every time I need to mark something.

**Describe the solution you'd like**
A checkmark or editable quantity in the overlay.

**Describe alternatives you've considered**
None as far as I know.

**Additional context**
None as far as I know.

**Comment by Supamiu** [comment]
Hi, the overlay is meant to be readonly to avoid having to synchronize both states, as they are really not working the same way. The best way to have it work as you wish is to use the autofill feature, this way your items will be marked as done when obtained, and you won't even need to reach the main window at all.

I'm closing this as won't do, because of how much refactoring it'll need to have it working without having a really bad performance impact.
