### ISSUE TITLE
feat: filter inventory by job

### ISSUE THREAD

**Issue by olanystrom** [ffxiv-teamcraft/ffxiv-teamcraft#2206]
Since we have inventory, I would like to filter on job.
All things in my inventory that can be used by PLD for example.

**Comment by Supamiu** [comment]
Hi, there is an issue template for feature requests in order to make sure we have enough details to do some research and understand the need and if it's worth dev time.

Please open another issue following the template and giving as much details as possible if you want to give this a chance, because my reply has more content than your original message, and I have no idea what you really want to have implemented.

You can also join the Discord server to discuss this with us if it requires more interaction than a github issue.
