### ISSUE TITLE
Bug: pricing mode manual input not updating

### ISSUE THREAD

**Issue by AcidAshe** [ffxiv-teamcraft/ffxiv-teamcraft#2207]
**Describe the bug**

When trying to manually update a price value for an item in pricing mode, it does not update the item's value in other lists.

**To Reproduce**

1. Open any list's pricing mode.
2. Change the price value of any item.
3. Open any list that has the same item altered in step 2, and open pricing mode.
4. See that the price value for the item was not updated in the list opened in step 3.

**Expected behavior**

Updating an item's price value in pricing mode in any list will also update that item's price value in all other lists.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop App
 - Version 9.5.11

**Additional context**

I do not use the "Fill from marketboard" button at all. All price values I use are manually entered.

**Comment by Supamiu** [comment]
This is not something that's going to be fixed, because each item in each list is independant and it's not something that's planned to change.

The main reason being that the item can be from a different source, different price at different times, you might also want to keep track of how much it did cost back when you made the list, etc.
