### ISSUE TITLE
feat: Turn off inner Scrollbars in Pre-Craft Section of a List

### ISSUE THREAD

**Issue by smcgit** [ffxiv-teamcraft/ffxiv-teamcraft#2208]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a big list and there are scrollbars inside scrollbars. I feel like that multiple scrollbars are unnecessary as the sections in a list can be collapsed anyway.

**Describe the solution you'd like**
Remove the scrollbars of Tier 1, Tier 2, etc. sections of the pre crafts and display them as a whole without any scrollbars. Or at least a setting to turn these off.

**Additional context**
![image](https://user-images.githubusercontent.com/40058557/155824600-efb6f3bf-406d-4762-81e6-d640380152a4.png)

**Comment by Supamiu** [comment]
Hi, there is a setting to change the way this behaves, but keep in mind these scrollbars are here for better initial loading time on larger lists, so disabling them will make the list load slower.

Large lists over 50 final items are also not recommended, because of all the performance issues they can cause, making them unsupported (meaning we won't add features for large lists specifically, but if you can live with their current state, it's fine).

![image](https://user-images.githubusercontent.com/11519203/155882125-1f0d7310-3f44-464e-ba96-f7104b9bb064.png)
