### ISSUE TITLE
bug: public profile not loading correctly

### ISSUE THREAD

**Issue by FinlayMaciver** [ffxiv-teamcraft/ffxiv-teamcraft#2236]
**Describe the bug**
Public profile isn't loading correct crafter/gatherer levels as well as not loading your fishing rankings. Lots of console errors too ("ERR_BLOCKED_BY_CLIENT")

**To Reproduce**
1. When logged in, hover over your name in top-right and click Profile
2. Click 'Open Public Profile'
3. See incorrect levels + constant loading of fishing rankings pinwheel.

**Expected behavior**
Levels should be correct (i.e all my DOH/DOL are 90 but my public page shows 80s and 0s). Fishing rankings should also complete loading.

**Desktop (please complete the following information):**
Occurs in both desktop app and Chrome browser.
- Desktop App: Version 9.5.16 - Windows 11
- Chrome: Version 100.0.4896.75

**Comment by Supamiu** [comment]
Hi, thank you for your report.

Having the fish rankings loading forever is *kind of expected* because fish rankings feature has been disabled entirely to prevent databse overloading. However, your profile should display the correct levels based on the values you entered in your profile editor page, make sure these values are accurate.

I noticed the job icons weren't loading properly tho, and I'm going to fix that.
