### ISSUE TITLE
feat: Don't create a desktop icon every update

### ISSUE THREAD

**Issue by jjspace** [ffxiv-teamcraft/ffxiv-teamcraft#2255]
**Is your feature request related to a problem? Please describe.**
I delete the desktop icon for Teamcraft every time I see it but it keeps showing up and seems to be every time it updates. I don't use or like desktop icons and opt out every time a program tries to add one or just delete it if they do anyway.

**Describe the solution you'd like**
Don't re-create the icon if it's gone. I don't know of any other programs that keep re-adding it on every update, especially without asking the user if they want it or not

**Comment by Supamiu** [comment]
Hi, there is a setting for this in the settings popup, but overall, this is due to the fact that the setup is an all-in solution that does just everything for us, because by us I mean me, since we do'nt have a team, it's just me ^^

Sorry if this is an annoyance, but unless the setting works properly or someone manages to make a PR to fix it, I can't do anything about that.
