### ISSUE TITLE
feat:Wish more features related to Voyage.

### ISSUE THREAD

**Issue by HeavenPolicy** [ffxiv-teamcraft/ffxiv-teamcraft#2310]
Wish more features related to Voyage.
I hope that the Teamcraft will be able to read the experience value and configuration of Voyages, and calculate the most suitable upgrade route for each Voyage at the same time.

Calculate the materials and quantities that are likely to be obtained on each voyage.
After select the parts of Voyage and sailing rote, I hope it can also automatically calculate the materials and their quantities that might be acquired, and show the price of these materials on Universaliy to estimate the earnings.

Some functions for total-material-cost calculation. 
For example, if I chose a Voyage part or a piece of equipment, Teamcraft will automatically calculate the gold coins which all materials needed to purchase from the trading board; or after have had a part of materials, the other materials' total price on the trading board. Besides, I also hope that it can be showed all the real-time price of these materials at different regions in Data Center at the same time.

 Voyage related functions are very important to me, if it can be achieved, thank you very much.

**Comment by Supamiu** [comment]
Hi, this issue is not following the feature request template and most of the things being asked are not possible with the currently available free time.

Would be a nice contribution from external devs but that's not going to happen unless you follow the template.

Please open a new issue that follows the template if you want this to be worked on, one issue per feature is also needed, as having one issue that says "I'd like this, oh and this would be cool too" makes it hard to track development.
