### ISSUE TITLE
bug: retainer ventures stopped working in latest update

### ISSUE THREAD

**Issue by retep998** [ffxiv-teamcraft/ffxiv-teamcraft#2313]
**Describe the bug**
When using Retainer ventures, after filling out the information, and clicking Search, the loading thing appears for a couple second then vanishes with no results appearing.

**To Reproduce**
1. Go to Helpers -> Retainer Ventures.
2. Select a retainer to fill in the data, or fill in the fields manually. I have mine set to Paladin/90/578/Faerie for reference.
3. Click Search.
4. Observe lack of results appearing.

**Expected behavior**
I expect to see the search results actually appear so I know what I should send my retainer out to acquire.

**Desktop (please complete the following information):**
Using standalone v9.7.4 of Teamcraft App on Windows 10

**Comment by karpik123** [comment]
I have had continuous problems with https://universalis.app/ in past couple days, even accessing it via browser usually borks. I think poor tool is creaking under the crafting pressure. As a result - in my case at least, - Teamcraft's Pricing Mode is broken, it attempts to fetch prices but timeouts not-so-gracefully and just gets stuck. Retainer ventures require item prices to work as well, so I thought I'll mention it here instead of creating a new issue.

**Comment by Supamiu** [comment]
As described by karpik123 above, this is due to Universalis and should be fixed now, since Universalis is back up 😄
