### ISSUE TITLE
bug: can't change restday in workshop

### ISSUE THREAD

**Issue by Velvet-888** [ffxiv-teamcraft/ffxiv-teamcraft#2429]
**Describe the bug**
I am unable to change Restday Number 1 since I put it on Tuesday. On Monday, the day after does not yet appear, and once the Tuesday begins with the new week, I can't click on 

**To Reproduce**
I can't reproduce it, since the restday Number 1 cannot be changed

**Expected behavior**
To change both Restday Number 1 and Number 2 on the days I wish.

**Screenshots**
![image](https://user-images.githubusercontent.com/121875104/210370290-14b534ba-2853-4aeb-8979-0912e8f85d10.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, desktop app]
 - Version [9.9.14]

**Comment by Supamiu** [comment]
You can change rest day 2 but not rest day 1 and this is by design.

We can't predict anything for day 1, and since it has already started when the week starts, you won't even be able to run a full 24h crafts cycle on it, which means it cannot be optimal, not even useful at all.

This is why first rest day cannot be changed, because it makes no sense to not rest on first day of the cycle, and it will never be optimal not to rest on first day, no matter what.
