### ISSUE TITLE
feat: add proxy support for package capture (global server)

### ISSUE THREAD

**Issue by liuyuran** [ffxiv-teamcraft/ffxiv-teamcraft#2463]
**Is your feature request related to a problem? Please describe.**
In some where like china, cannot resolve or connect to that domain: raw.githubusercontent.com
Well, I'm a chinese player but playing the global server, so...
When I open teamcraft, I'll see alert window tell me failed to resolve that domain.

**Describe the solution you'd like**
Add a proxy support to pcap-ffxiv.

**Describe alternatives you've considered**
After clone code and read it, I think it's because `downloadJson` function in `pcap-ffxiv` lib not use electron proxy settings.
So I try to do these change:
1. Add a configuration in ```CaptureInterfaceOptions```
```
export interface CaptureInterfaceOptions {
	...
	getFetch: () => (string) => Promise<any>;
	...
}
```
2. Move the implement to default value of config in ```CaptureInterface```
```
        constructor(options: Partial<CaptureInterfaceOptions>) {
		...
		const defaultOptions: CaptureInterfaceOptions = {
			...
			getFetch: () => (uri: string) => {
				return new Promise<any>(resolve => {
					const req = https.request(new URL(uri), (res) => {
						const data: any[] = [];
						res.setEncoding("utf8");
						res.on("data", (chunk) => data.push(chunk));
						res.on("end", () => resolve(JSON.parse(data.join(""))));
					});
					req.end();
				});
			}
		};
		...
	}
```
3. Change download function in ```json-download```
```
export function downloadJson<T>(uri: string, getFetch: () => (string) => Promise<any>): Promise<T> {
	return new Promise((resolve, reject) => {
		getFetch()(uri).then((data) => {
			resolve(data);
		}).catch(e => {
			reject(e);
		});
	});
}
```
4. Replace with another download implement ( but only support HTTP proxy so not create PR, maybe someone have a better way? ) in ```PacketCapture```
```
  private fetch: (string) => Promise<any> = (uri: string) => {
    return new Promise<any>(resolve => {
      request.get(uri, (error, response, body) => {
        resolve(JSON.parse(body));
      })
    });
  };

  private getFetch: () => (uri: string) => Promise<any> = () => this.fetch;

  const options: Partial<CaptureInterfaceOptions> = {
      ...
      getFetch: this.getFetch,
      ...
    };
```

5. Add env in ```ProxyManager```
```
  setProxy(win: BrowserWindow, params: { rule?: string, pac?: string, bypass?: string }) {
    ...
    process.env["http_proxy"] = params.rule || this.store.get('proxy-pac', '');
    process.env["no_proxy"] = params.pac || this.store.get('proxy-pac', '');
    ...
  }
```

**Additional context**

**Comment by Supamiu** [comment]
Hi, many people are playing from china and can load this just fine using their proxy configuration.

Because the pcap-ffxiv lib will fetch based on the region given to it (See https://github.com/ffxiv-teamcraft/pcap-ffxiv/blob/main/src/pcap-ffxiv.ts#L261-L264).

Having the library (which is open source and not just for TC) provide a way to change how things are fetched opens the door to too many bugs possibility imo (people missusing it, having to provide it in the first place, etc).

The best option would be to just make a redirect in your hosts file or something to fetch this from another source. Because the amount of people who are playing global from china is not that high and introducing a breaking change for all the other pcap-ffxiv users that may not even use electron is not something I want to do.

I also found this: https://github.com/hedzr/mirror-list which looks like it has some github mirrors for you.

**Comment by liuyuran** [comment]
Sadly that it's not working for me :(
Ok, I'll try to find another way to fix that without change code.
