### ISSUE TITLE
bug: island workshop craft item themes doesn't load for ZH locale

### ISSUE THREAD

**Issue by Jarvie8176** [ffxiv-teamcraft/ffxiv-teamcraft#2465]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
creat item themes for ZH (and probably KO) locales cannot load due to a missing file.

**To Reproduce**
1. change locale to ZH
2. open island sanctuary -> workshop tab
3. theme texts in workshop planning (if "Display category and craft time of items in planning" is checked) or list of items are not updated.

**Expected behavior**

themes should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/3547456/215176762-6da349b1-e9d8-40a3-a123-f85d5a16cbaf.png)

**Additional context**
`lazy-data-effect.ts:getUrl()` tries to load an asset file thta does not exist for ZH or KO locales.
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/apps/client/src/app/lazy-data/%2Bstate/lazy-data.effects.ts#L78-L79

this line tries to load `lazyFilesList["zhIslandCraftworksTheme"]` but the key does not exist, there is only `islandCraftworksTheme`

(in fact all the island-related asset files are missing in `apps/client/src/assets/data/[zh|kr]`
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/tree/staging/apps/client/src/assets/data/zh

**Comment by Supamiu** [comment]
Please avoid double reporting (on discord and on github) issues. 

As explained on Discord, this is because this content doesn't exist in zh or kr yet and you're using Teamcraft with ZH translation on global region, which creates issues like this one.

It could be solved by adding fallback behavior in here but it'd add quite a lot of complexity. A PR would be welcome for that tho 😃
