### ISSUE TITLE
bug: uninstallable in wine (incorrect "run as administrator" detection)

### ISSUE THREAD

**Issue by draeath** [ffxiv-teamcraft/ffxiv-teamcraft#2492]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
The tool is not installable via Wine / Codeweaver's Crossover. This is because the setup tool (incorrectly, in this case) detects being run as administrator.

**To Reproduce**
1. Attempt to run the installer within Wine or Crossover
2. Observe error message

**Expected behavior**
Correct operation.

**Screenshots**
![image](https://user-images.githubusercontent.com/987449/218244946-d677b50c-eda0-4130-b9af-bb631df9a52c.png)

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed x86_64, via Crossover Linux 22.0.1 (Wine 7.7)
 - Browser: N/A
 - Version: 10.2.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
There would ideally be a means to bypass this detection, such as a command line argument or treating it as a warning rather than an error. Alternative to code changes, a non-installer release artifact might be welcome if reasonable.

**Comment by Supamiu** [comment]
Sorry but we do not provide support for linux users, this is because I have no linux platform to test on.

Plus we don't even make the installer ourselves, it's packed using squirrel, I highly recommend building your own installer using the codebase, editing package.json's builder config following https://www.electron.build/configuration/linux and then run `yarn build:electron-prod` and finally `yarn electron-builder -l`

**Comment by draeath** [comment]
> Alternative to code changes, a non-installer release artifact might be welcome if reasonable.

I'm guessing this is a no as well then, @Supamiu ? (i'm assuming you didn't read all the way through)

**Comment by Supamiu** [comment]
It's not a no, it's the same answer: feel free to PR that but I won't do it myself ^^ also mostly because storing such an artifact would be annoying, as it's not a single exe file that's copied when installed.

Again you can easily just clone and build yourself, and that would be way better than any build I'd automate in the windows CI build as it'd be built on Linux.

**Comment by draeath** [comment]
Thanks. Just checking, I would have assumed one could just add a step in the CI to archive everything before building/bundling the installer.

I'll have a look at building it on my end. Thanks!
