### ISSUE TITLE
feat: Triple Triad Tracker

### ISSUE THREAD

**Issue by niall-san** [ffxiv-teamcraft/ffxiv-teamcraft#2520]
**Is your feature request related to a problem? Please describe.**
It's a pain to have to figure out which Triple Triad cards I am missing and which NPC or duty I need to battle/do to get the card.

**Describe the solution you'd like**
A Triple Triad card tracker that would automatically fetch which Triple Triad cards the player already has and provides details about which duties or NPC battles are required for the remaining cards.

**Describe alternatives you've considered**
There are websites currently that can already be used to track cards, however they require manually updating and do not always make it easy to view how to get the remaining cards.

**Comment by Supamiu** [comment]
https://ffxivcollect.com/ is the best website for that, and I'm not going to implement it in TC :)

Because updating card collection automatically is not something that should be done in TC (if it can be done at all, I have no idea how it's sent to the client). So even if it was in TC, it'd require manual updating them, and most sources are also handmade in most sites, because it's not easy at all, even nearly impossible for some, to extract this data from the game files.

**Comment by niall-san** [comment]
Thanks for the response. I did not realise that it was not possible to get the TT card data from the packet capture. I will stick with using the websites then :)
