### ISSUE TITLE
bug: bitdefender crashes if packet capture is enabled

### ISSUE THREAD

**Issue by ghost** [ffxiv-teamcraft/ffxiv-teamcraft#2550]
I think the title says it pretty much but yeah.. If you are using BitDefender and have packet capture enabled, the program just crashes instantly. I'm not sure if its the antivirus or advance threat feature thing BitDefender has that's making it crash, but something definetly is. I had to disable them both and now it works, which is obviously not an ideal thing.

**To Reproduce**
1. Have BitDefender Antivirus
2. Have latest version of Teamcraft with packet capture enabled
3. Start Teamcraft
4. Watch it crash and burn

**Expected behavior**
To not crash.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 10.3.12

**Additional context**
I think BitDefender sees something in the new code as malicious because it even quarantined the updater when I was updating to 10.3.12

**Comment by Synobis** [comment]
I have this issue as well. It is exactly because BitDefender thinks the program is Malware. You can't whitelist it either. It will do this *EVERY* update. It's the most annoying thing. The reason for this is how Teamcraft does updates. It's downloaded into a separate folder in AppData/Local/ffxiv-teamcraft/app-*.*.* . Even if you tell BitDefender to whitelist /ffxiv-teamcraft it won't help because it won't read that whitelist recursively into the newly made update folders.

Every new update I have to come to github, download the new installer, and manually update teamcraft because BitDefender deletes the .exe's. Does not quarantine them, just straight delete. I use teamcraft quite a bit but this is it's most annoying thing. I have found no solution even after calling BitDefender. 

The only one I could think of would be for updates to use the same folder every time. Then the whitelist would actually work.

**Comment by Supamiu** [comment]
There's nothing I can do about this.

Teamcraft is now using process injection to capture packets, due to the latest packet changes regarding compression that were introduced with 6.35, it's not the only way to properly capture packets.

BitDefender thinks injection = malware because it's stupid. Best you can do is whitelist the whole Teamcraft folder in `%LocalAppData%/ffxiv-teamcraft` instead of the exe but that's about it.

Or use an antivirus that isn't stupid ^^

**Comment by Supamiu** [comment]
Yes, it started happening with the changes that have been made to handle FFXIV 6.35's packet changes, so it started with 10.3.10 and will have to stay like that for the next updates.

Hence why it'll do it with every updates 🙂.

I added a command to the discord server about BitDefender, which says :

**Teamcraft desktop app is blocked by BitDefender**
One way this can be fixed is by whitelisting %LocalAppData%/ffxiv-teamcraft/app-X.X.X/FFXIV Teamcraft.exe.
This is only temporary as the path to the exe file changes with every update, that's how Squirrel installer does it.

**Another way to fix this is to use another antivirus, BitDefender is just lazy**
BitDefender is triggered by Teamcraft's packet capture system because it calls win32 api to inject a dll in the game process, which makes BitDefender react immediately.
It doesn't check what's injected or how it's used, injection = trigger, which is just lazy.
