### ISSUE TITLE
Bug: Lists include precursor inputs for items that are in the "Vendors" section

### ISSUE THREAD

**Issue by AzariahAeroborn** [ffxiv-teamcraft/ffxiv-teamcraft#2554]
**Describe the bug**
If you're working on a project that has a number of inputs that can be purchased directly from a vendor but are also craftable, the list will include counts for both purchasing the higher stage item and for the inputs required to craft that item, leading to purchasing/gathering too many resources.  This is most noticeable with the recipes for FC Workshop items such as airships or submarines.

**To Reproduce**
1. Create a new list
2. Add the Unkiu-class Bow as an item to craft
3. Observe that the Vendors list includes 30 Steel Rivets and 90 Steel Ingots
4. Mark the 30 Steel Rivets as complete
5. Observe that the number of Steel Ingots acquired changes to 30/90

**Expected behavior**
The initial list only contains 60 Steel Ingots (the 30 used for crafting Steel Joint Plates and the 30 directly input into the final product), and does not include the quantity of any items used in a crafting recipe for other items purchased from a vendor.  (This is also really noticeable with the amount of Mythril Ingots to purchase and the Mythril Ore to gather, or the quantity of Iron Ore and Bomb Ash to purchase, which is largely from the Steel Ingots / Steel Rivets being purchased).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest

**Comment by Supamiu** [comment]
Hi, 

This is what the "can skip XX" tag is for, to tell you that you can skip 30 of this item. The goal of the list being to display every item needed, showing 60 instead would be a mistake because if the user wanted to craft everything from raw material, they couldn't do it.

![image](https://user-images.githubusercontent.com/11519203/225548773-594b2d33-73c1-4310-b9de-e91e6b61ee81.png)


Also, you may want to tweak your layout to have some specific behavior that matches your needs, see https://wiki.ffxivteamcraft.com/base-features/layout-system

**Comment by AzariahAeroborn** [comment]
It appears that the "Can skip" tag does not show up with a customized layout -- I use a customized layout I've titled "Gathering" that has the same settings as the Default layout except I've cleared all the "Hide zone duplicates" options and have the Pre-crafts section sorted by NAME DESC instead of JOB ASC, and the "Can skip" tag doesn't appear on the Gathering layout.  

Also, the "Can skip" tag does not show in Minimalist display mode even on the Default layout, nor does it show for the gatherable materials for purchasable ingots on the Default layout (if you view list https://ffxivteamcraft.com/list/H0cnpvUbU0Svnkl8gK4s - the Mythril Ore section of that list shows 1134 Mythril Ore required, but all of the ore is used for Mythril Ingots or Mythrite Nuggets, which can be purchased directly, and a good number of the Ingots and Nuggets can be skipped as well (which does show the tag but only on a non-customized layout).

It's also pretty confusing that the "Crafts and Timed First" layout groups vendor purchased craftable inputs in the "Pre crafts" box and does not show them in the "Vendors" box, while the "Default" view does the opposite.  In addition, I do not see any "Can skip" tags on the "Crafts and Timed First" layout.

I don't see any option in the layout configuration to toggle whether that "Can skip" tag should show or not.  And adding "NOT CAN_BE_BOUGHT" to the Gathering section doesn't do anything to remove the Mythril Ore from the displayed amount or otherwise show that I shouldn't be gathering that because I'm purchasing it from a Vendor.

Ideally, I'd expect the behavior to be similar to what Garland Tools does - you can specify a source for the item, and if you specify "vendor" then it shows the amount to buy from the vendor and does not show acquiring inputs required to craft the item in any fashion.  If doing that on a per-item basis is not desirable, then at least I would expect to see an option at the top of the list (next to "Only show what I can do" et al) or in the view configurations, and I would expect the default behavior of all views to be to not show items I don't need because I'm purchasing a later stage (or at the very least clearly indicate what I shouldn't be gathering or crafting via the Can skip tag) .

**Comment by Supamiu** [comment]
Can skip will only show in vendor layouts because it only relies on vendor stuff. It also doesn't show in minimalist because it's... minimalist ^^ so showing every possible detail in here would be against the minimalist behavior entirely.

I don't want to implement what GT does regarding item sources because that would mean relying on the user to configure it per item and that's not very sexy in terms of UX.

As for the layout itself, you should hop on the discord server to get more help, because github is too slow for that, but I think this is due to how you combined your `NOT CAN BE BOUGHT` (should probably be the first one in the chain, followed by `AND` and then the current filters for the panel).

I believe we should fix that by providing a better approach for the canSkip logic, instead of having a way for users to maintain it and having to explain everyone how to do it (like it's in the pins of the GT discord server)

**Comment by Supamiu** [comment]
I have made some changes to the canSkip system to have it display even when not using NPC breakdown display mode for your panels.

I believe it's be even better to have it consider the list as a whole but then it becomes hard to implement without it being a big performance issue.

For instance, you need 1134 Mythril Ore but they're all used for Mythril ingot, it doesn't mean they can be skipped, just that if you decide to purchase the ingots, the ores will be a nice skip to do. Which means that each item should check what uses it (like ore should check Ingot) and then check which panel it's being listed in, to decide if it's worth showing the skip tag or not.

You can easily see how this could end up being a performance issue ^^

**Comment by AzariahAeroborn** [comment]
Thanks for the changes.  This does make "Can skip" show in my customized layout as well, so that's a big help.
