### ISSUE TITLE
Please consider adding optimization support for the 4th island workshop.

### ISSUE THREAD

**Issue by spider623** [ffxiv-teamcraft/ffxiv-teamcraft#2629]
The way the 4th work works, you have to use different orders to maximize weekly profit.

If possible, could you consider adding separate recommendations for it like the one from the overseas casuals in Discord?

**Comment by Supamiu** [comment]
Hi,

First of all, there's a template for issues, please use it instead of just two sentences, it's very important for us.

Optimizations for the 4th workshop are being discussed but while it's fairly easy to do in a manual way (like in OC Discord server), automating it isn't that easy and it also includes an UI issue that is: how to display it properly.

If you have ideas or want to contribute to that, please prefer the #feature-requests channel on the Teamcraft Discord server 🙂
