### ISSUE TITLE
Feat: Add Contribution Amount in Team Lists

### ISSUE THREAD

**Issue by Aurora8orealis** [ffxiv-teamcraft/ffxiv-teamcraft#2707]
**Is your feature request related to a problem? Please describe.**
When Using the Team Feature, having multiple people work on the same list, looking up the amount of collected items can get confusing.
There is no indicator that shows who contributed how many items to the list, making planning, especially when items get moved around between players or inventories messy.

**Describe the solution you'd like**
When showing an Item like
Hide 10/20
When hovering over the Amount collected, show a list of who added how many Items
So if I add 5 Items and a friend adds 5 Items, the Information would show
Name1: 5
Name2: 5

**Describe alternatives you've considered**
An addition button besides the "add/remove given amount" that gives a popup window with a list of source of what player added how much to the list

**Additional context**
Just badly main image of how the popup could look like when hovering over the collected amount.
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/102928656/3ef73ede-3e22-4e18-a9c3-abcce8102128)

**Comment by Supamiu** [comment]
While I understand the need for this feature, the implementation requires way too much database usage, meaning that it'd either make us build large objects to store in database or smaller ones that need to be updated often.

In both cases, it's really bad for the database usage, which means bad for the pricing.

We used to have an history system but it's no longer a thing because of that, removing history system cut database costs by ~60%.

What you can do is to enable discord webhook and use the webhook channel as an history system, which also shows when each player added things, but except if there's a miraculous solution to hold tens of thousands of new entries per minute for a low cost, I don't see this becoming a thing, sorry.
