### ISSUE TITLE
bug: Version 11.3.11 crashes at startup

### ISSUE THREAD

**Issue by OffworldMiningCompany** [ffxiv-teamcraft/ffxiv-teamcraft#2925]
**Describe the bug**
Version 11.3.11 crashes at startup.

**To Reproduce**
1. Try to start the application.

**Expected behavior**
The application starts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: n/a
 - Version 11.3.11

**Additional context**
```
Uncaught Exception:
Error: The Specified module could not be found.
\\?\C:\Users\User\AppData\Local\ffxiv-teamcraft\app-11.3.11\resources\a...\injector.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
...
(C:\Users\User\AppData\Local\ffxiv-teamcraft\app-11.1.11\resources\app.asar\node_...:48) at Object.<anonymous>
(C:\Users\User\AppData\Local\ffxiv-teamcraft\app-11.1.11\resources\app.asar\node_...:37)
```

Sorry, can't post screenshot as it contains personal information.

**Comment by Elettronik** [comment]
I have the same error and windows defender seems to find a malicious software in this release

**Comment by SwissHope** [comment]
Having attempted to install the current version, I too have had Windows Defender report that there is malware in the package. Specifically, Windows Defender is highlighting it as the Trojan Win32/Wacatrac.B!ml. It located this in the injector.node at 
`C:\Users\user\AppData\ffxiv-teamcraft\app-11.3.11\resources\app.asar.unpacked\node_modules\@ffxiv-teamcraft\dll-inject\build\Debug\injector.node`.

**Comment by Lalalavicious** [comment]
We are already aware of the "malware flagging," and it's been discussed on the Discord at length! It's not actually _this version_ that is being flagged; the previous version suddenly began getting flagged about a week ago, when we hadn't updated for around a month.

### THIS IS ABSOLUTELY JUST A FALSE POSITIVE.
We've had this show up multiple times before, but usually only from one individual antivirus, maybe two, at a time. Please do what you can to inform your AV that this is a false positive! This is all open-source, as you know because you're on the Github for it, so feel free to confirm. Nothing has changed; the detected item is basically the injector that has been in use since FFXIV 6.35 (when SE changed packet structure), with a couple bug fixes from ages ago.

Until all AVs acknowledge this as not being dangerous, please simply whitelist `%localappdata%\ffxiv-teamcraft\` (by default, this is `C:\\Users\[username]\AppData\Local`) in your individual antivirus. You may also need to un-quarantine the current version's installer in order for it to install properly; when it doesn't properly install, you get the crash with a missing file, as at the start of this thread.

We're sorry about this inconvenience, but we literally didn't change anything to cause in the first place, so. =(

**Comment by nivintw** [comment]
Not to dismiss the good conversation about the malware false-positive flag above, but I too am seeing the desktop app crash on startup and it's unrelated to the false-positive about malware (which I have not yet seen myself)

**Comment by nivintw** [comment]
This is making the desktop app completely unusable FYSA. I manually down-graded to a prior release and the app auto-updated when it closed and i'm back to it crashing on startup. 

If someone can just confirm they are looking into this that would be hugely appreciated.
Thanks for everything you do!

**Comment by nivintw** [comment]
I was mistaken; this is in fact related to windows defender deleting the relevant file. My apologies.

**Comment by dljvette** [comment]
For those impacted by Windows Defender's false positive, you can create an Allow List "Exclusion" by following MS's documentation: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

As @Lalalavicious points out, `%localappdata%\ffxiv-teamcraft\` is the directory to exclude and may require a reinstallation or other action to remove the targeted file from quarantine.

I was able to get Teamcraft back up and running following the Exclusion process and reinstallation. Hope that helps.

**Comment by Supamiu** [comment]
#2926 is going to be our "main AV issue", closing this one.
