### ISSUE TITLE
feat: discord bot for gathering nodes (and more?)

### ISSUE THREAD

**Issue by tddesjardins** [ffxiv-teamcraft/ffxiv-teamcraft#454]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
A discord bot that can interface with lists to alert users via a text channel that nodes required for a list are about to spawn. Could also add a summary of incomplete items in a list.

## What is the use case for this feature?
People who do not use the teamcraft website for whatever reason can benefit from some of its tools in group crafting. For example, PS4 users who might not have a computer nearby while they play.

**Comment by MDlumia** [comment]
this actually seems like  very good idea actually.  +1

**Comment by AcidAshe** [comment]
I do agree this would be amazing, but have NO IDEA how it would be achieved. However I can offer the usual "flow" suggestions:

1: sign up with the discord bot via userID and some sort of access key that your TC account will generate for you? (a link to add the bot to a server could be pinned somewhere)

2: on the alarms page, for each list of alarms, there will be a button(?) to bring up an interface to allow you to enter details on bot interaction?

3: you will be asked which discord server(or DMs) you want them posted to, and which channel? Also possibly an option for what roles to tag? since the bot would have to be smarter to know all channels and tags, the input method would just be as if you were tagging in the discord mayhaps? the bot should already have your discord tag from the verification process where you gave it your userID and key. example:
     Channel: #teamcraft-alarms (You would say to DM you here also instead if you like)
     Ping: @gatherers @crafters 

4: the bot will then either post the alerts to the channel specified with the role tags specified, or will DM them to you

**Comment by Supamiu** [comment]
The main issue here is that there's no server-side code, meaning that you'd need to have Teamcraft running somewhere with your account logged in. Or an implementation of the alarms system inside a google cloud function, running in background, ticking each eorzean minute, which is a lot of calls per day, that would increase the server costs by a bit. Wouldn't need to scale with users tho, so....

Anyways, I find it interesting and useful, but it requires a lot of work for now, I don't see a proper solution that would be easy.

I guess @mattantonelli would have a better idea of the discord part of the bot, as I never made a discord bot.

**Comment by mattantonelli** [comment]
A Discord webhook would probably be good for the initial stages of this. Discord has a relatively simple OAuth flow that would allow you to send messages to a specific channel for a given user's alarms. If you wanted to really finely tune this, you could create a traditional bot which would allow you to configure things from the Discord server. This would require some sort of auth/token flow on TC's end, as well as hosting.

But the big issue here as @Supamiu pointed out is TC is all client side code, so at the moment there is nothing available to "watch" the user's alarms and push the updates out to Discord.
