### ISSUE TITLE
feat: Managing your Lists with a discord bot

### ISSUE THREAD

**Issue by Kredus97** [ffxiv-teamcraft/ffxiv-teamcraft#616]
Nowadays we all try to get all-in-one solutions. Thankfully Discord is a platform that offers stuff like that with bots. We currently use Teamcraft to manage a large scale Craft, yet when we discuss whats still needed and what not, we always have to check the website. So heres the idea:

Maybe implement a bot that could provide us with information aswell as fill entries over discordcommands.

For example:

Creating a New List:

Many bots have a feature to search for youtube videos, giving a keyword as input and then having the option to choose from a list via numbers 1-10. Maybe the bot could use the keyword to do a search on and display the results in the same way:

!TC search Keyword
TCBot: Here are the results for "Keyword"
1. Keyword
2. odder keyword
3. unending keyword
4. Keyword is in me

Now you could set a project:
!TC list add 4
TCBot: "added "Keyword is in me" to list"

TCBot could also show a list and what it contains:

!TC show list x
TCBot: *formatted box with ingredients and how much is there and still needed*

Considering people have different projects they actually work on, the bot would need to handle different lists. maybe that could be solved by having multiple options. like having an active list system where you set your default list and adding the destination within the command itself.

!TC set list x
TCBot: "list x is now your default list"

Then filling the list with the needed items:

!TC add item x 10
TCBot: "10 x has been added to list x"

Lets say someone wants to contribute to his own personal list, thats actually not set as active:

!TC additem 10 x list y
TCBot: "10 x has been added to "list y"

If someone made a mistake, you could revoke the entry with "!tc revoke entry". I dont know the technical doability of deleting entries, but it could be considered. Maybe you could assign a consecutive number to a command and provide that with every action you did with the bot, giving players the option to revoke the entry with that specific number.

Now as an additional thing, you can add the Discord Tag onto the list, like if someone shows the list, the bot would show stuff like "Item x: 10/20 needed. 10 items Submitted by: Kredus". Discord could just grab the discord tag, send it along with the list entry and make a note or something like that on TC.

Those are some ideas that were floating my mind. If I find new and better features that coud be implemented aswell, i will update this request!

**Comment by Supamiu** [comment]
@mattantonelli will be the best source of information for everything related to commands.

By reading this issue, I find a lot of stuff useful but anything that includes writing will be a big pain to do, mainly because write requires permissions integration, which means auth via the bot, and this feels way too hard for me right now.

Another hard part with writing is ingredients management. let's say you want 3 ingots and each ingot requires 3 ores, if you set 2 ingots as done, the app needs to set 6 ores as done too (and as used, since you just used them for your craft), this logic belongs to the front atm, doing it again in GCF feels wrong as it needs a lot of logic stuff (thanks CUL and ALC crafts).

I really see a lot of useful stuff that could be done with the bot, not to mention what acchan mentionned: the event hooks. That being said, a lot of writing operations will be gated behind the logic being frontend, not backend since there's no backend ^^ so replicating this kind of logic in backend seems too hard just to avoid interactions.

But having read operations in the bot is a really nice and easy idea 👍

**Comment by MDlumia** [comment]
as requested. MDlumia Today at 1:39 PM
example my fc im in has a crafts request channel
i could set a command in there to have requested items added to a workshop like "FC requests"
each command would be a list

MiuToday at 1:43 PM
Readonly, yes
but writing via a command requires that you have the rights to write what you're trying to write
So it requires auth, and that's the hard part
other than that, only ingredients are kinda hard for the bot
RaelysToday at 1:44 PM
@Miu once you handle oauth on TC's side you can map their discord user id to their teamcraft user id
then execute all future commands from that user id as that TC user

MiuToday at 1:45 PM
TODO: discord oauth lmao
RaelysToday at 1:45 PM
it's super easy
and you just need to auth one time and store their ID
M'Marrie Lumia (Mateus)Today at 1:47 PM
cause that would make things super easy for pure gatherers too. like !request Matsneeded  and it pulls up a list or such of mats needed  and maybe where to find them
RaelysToday at 1:50 PM
Just make sure you put "Miu smells" in the issue comment 


other ideas: ablity to query timers/ Gathering info/ FIsh info
Ablity to have bot post List updates Workshop updates/ ect to a DIscord ch. 
maybe have it able to Link Rotations from command. (ofc only rotations one have in  storage might work.) 
if i think of more ill post
