### ISSUE TITLE
Bug: Does not load when using NordVPN "Cybersec" (Desktop)

### ISSUE THREAD

**Issue by Kcasati** [ffxiv-teamcraft/ffxiv-teamcraft#950]
**Describe the bug**
Opening any Teamcraft page with NordVPN's "Cybersec" setting on will be stuck infinitely loading, on both the Desktop app or the Website.

**To Reproduce**
1. Turn on "CyberSec" in the NordVPN settings.
2. Open Teamcraft or any page within.
3. That's it.

**Expected behavior**
Teamcraft actually loading.

**Screenshots**
![CyberSec Setting](https://user-images.githubusercontent.com/51275754/58754537-189e7500-8487-11e9-80e9-dd7a705de9ad.png)
[Teamcraft loading (Desktop app)](https://cdn.discordapp.com/attachments/584510481214210050/584510562755411991/unknown.png)
[Teamcraft loading (Website)](https://cdn.discordapp.com/attachments/584510481214210050/584510817731608579/unknown.png)
[Both Loading](https://cdn.discordapp.com/attachments/584510481214210050/584515247587721218/unknown.png)

**Desktop:**
 - OS: Windows 10 Home 64-bit (10.0, Build 17763)
 - Browser: Chrome and Desktop App.
 - Version: Chrome Version 74.0.3729.169 (Official Build) (64-bit). Desktop App Version v5.4.13.

**Additional context**
This is not the biggest problem cause I can just turn "Cybersec" off, but I figure I should bring it to your attention.

**Comment by Supamiu** [comment]
Hey, thank you for the report :)

Can you reproduce with console opened please? I can show you how to start a dev build in order to be able to use a keyboard binding to open console.

This has been seen on the discord server and so far the best I can do is tell the users that have this issue to disable the VPN, now I know what they should disable inside the VPN thanks to you :)

**Comment by Kcasati** [comment]
Sure, but you will have to tell me how to do it.

**Comment by Supamiu** [comment]
I'm closing as supposedly fixed.
